config/routes.rb
Rails.application.routes.draw do
  
  delete "cocktails/:id", to: "cocktails#destroy", as: :destroy_cocktail
  get "cocktails/new", to: "cocktails#new", as: :new
  get "doses/new", to: "doses#new", as: :new_dose
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
     @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
    redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  def update
     @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
  end

  private
    def cocktail_params
      params.require(:cocktail).permit(:name)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  before_action :set_cocktail, only: [:new, :create]

    def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "doses/new"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private
    def set_cocktail
      @cocktail = Cocktail.find(params[:cocktail_id])
    end

    def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/destroy.html.erb
<h1>Cocktails#destroy</h1>
<p>Find me in app/views/cocktails/destroy.html.erb</p>

app/views/cocktails/edit.html.erb
<h1>Cocktails#edit</h1>
<p>Find me in app/views/cocktails/edit.html.erb</p>

app/views/cocktails/index.html.erb
<h1>Cocktails#index</h1>
<p>Find me in app/views/cocktails/index.html.erb</p>


<br>
  <% @cocktails.each do |cocktail| %>
    <p><%= link_to cocktail.name, cocktail_path(cocktail) %></p>
  <% end %>


<div class="btn btn-primary">
<%= link_to "Create new cocktail", new_path, :class => "btn" %>
</div>

app/views/cocktails/new.html.erb
<h1>Create your new cocktail!</h1>
<br>
<%= simple_form_for(@cocktail) do |t| %>
  <%= t.label :name %>
  <%= t.text_field :name %>
  <%= t.submit :class => "btn btn-primary"%>
<% end %>

app/views/cocktails/show.html.erb
  <%= link_to "Back to all cocktails", cocktails_path %>

  <div class="row">
    <div class="col-sm-12 col-md-6">
      <h3>Recipe</h3>
      <table class="table table-bordered">
        <tbody>
          <thead>
            <th>Ingredient</th>
            <th>Description</th>
            <th>Action</th>
          </thead>
          <% @cocktail.doses.each do |dose| %>
            <tr>
              <td><%= dose.ingredient.name %></td>
              <td><%= dose.description %></td>
              <td>
                <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <i class="fa fa-trash destroy_dose"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-sm-12 col-md-6">
      <%= render template: "doses/new", cocktail: @cocktail, dose: @dose %>
    </div>
  </div> 


<%= link_to 'delete',
  destroy_cocktail_path(@cocktail), :class => "btn btn-primary",
  data: { confirm: 'Are you sure?' },
  method: :delete %>

app/views/cocktails/update.html.erb
<h1>Cocktails#update</h1>
<p>Find me in app/views/cocktails/update.html.erb</p>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<h3>Add a new dose</h3>
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>